SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE detail_penjualan;
TRUNCATE TABLE pengiriman;
TRUNCATE TABLE pembayaran;
TRUNCATE TABLE penjualan;
TRUNCATE TABLE produk;
TRUNCATE TABLE gaji;
TRUNCATE TABLE karyawan;
TRUNCATE TABLE customer;
TRUNCATE TABLE supplier;
TRUNCATE TABLE size;
TRUNCATE TABLE kategori;

SET FOREIGN_KEY_CHECKS = 1;
